### ISSUE TITLE
codegen.py has bugs

### ISSUE THREAD

**Issue by ysangkok** [tomheon/grepy#1]
You are using an outdated version of `codegen.py`. It is causing me problems at runtime.

New version: https://gist.github.com/791312

Diff:

```
80c80
<     return ''.join(generator.result)

---
>     return ''.join(str(s) for s in generator.result)
331,332c331,335
<         self.write('return ')
<         self.visit(node.value)

---
>         if node.value:
>             self.write('return ')
>             self.visit(node.value)
>         else:
>             self.write('return')
```

**Comment by tomheon** [comment]
Thanks for the bug report, @ysangkok.  Do you have a snippet of code exhibiting the bug so I can add a test for this?

**Comment by ysangkok** [comment]
starimport.py:

```
from sys import *
```

throws.py:

```
from ast import parse
from codegen import to_source 
node = parse(open("starimport.py").read())
to_source(node)
```

execution:

```
% python throws.py 
Traceback (most recent call last):
  File "throws.py", line 4, in <module>
    to_source(node)
  File "/var/www/jsppa/compiledtests/codegen.py", line 80, in to_source
    return ''.join(generator.result)
TypeError: sequence item 2: expected string, alias found
```

**Comment by tomheon** [comment]
Thanks, tested and new version of codegen checked in.

**Comment by typeundefined** [comment]
Guys, has anybody created the pull request for codegen? I've just faced the same issue with the library and I wonder how to handle it best.

**Comment by tomheon** [comment]
Hey @typeundefined -- I pulled in the latest version as of the time of this bug report.

Are you still seeing codegen.py related issues?  If so, can you give me a code snippet to replicate?

Thanks!

**Comment by typeundefined** [comment]
Sorry, maybe I'm asking a stupid thing but I can't see the fix in https://github.com/andreif/codegen.
I've just downloaded the codegen library with pip and I can reproduce the issue...

**Comment by ysangkok** [comment]
@typeundefined how is that library related to grepy? I do not see the connection.

**Comment by tomheon** [comment]
Hey @typeundefined -- if you're seeing a problem with codegen.py, I think you need to head over to that project and ask there.  If you're using grepy and seeing a problem I'm happy to take a look, and possibly to update the version of codegen.py that grepy uses internally.

But I'm really not clear on what problem you're even seeing.

If you still think this is a grepy thing, please post a detailed description of what you're trying to do and what you're seeing--preferably with sample code--so that I can reproduce the problem.  Otherwise I'm really lost and just not sure how to help, or even if I can help!

Thanks!

**Comment by typeundefined** [comment]
Hi @tomheon!

I'm really sorry for bothering. The problem I'm seeing relates directly to codegen.py. BUT what I see is that this very ticket describes the same problem that I have AND you guys already have the fix :-) That's why I wondered if this fix had been submitted to codegen.py project.
